input:
  download_input_path: '../data'
  resample_scale_factor: 2
train:
  batch_size: 4
  learning_rate: 0.0001
  epochs: 50
  optimizer:
    name: adam  # or 'sgd'
    # Additional parameters for SGD (optional):
    # momentum: 0.9
    # dampening: 0.2
    weight_decay: 1e-5
  log_loss_every_nth_batch: 10 #default 10
  validate_every_n_epochs: 1 #default 1
fine_tune:
  batch_size: 4
  learning_rate: 0.0001
  epochs: 2
evaluate:
  batch_size: 4
  eval_score_path: '../results'
visualize:
  vis_num_images: 4
  vis_save_path: '../comparison_model_output_images'
  max_vis: 10
dataset:
  subset_percentage: 0.9
