input:
  download_input_path: '../data'
  resample_scale_factor: 2
train:
  batch_size: 4
  learning_rate: 0.0001
  epochs: 50
fine_tune:
  batch_size: 4
  learning_rate: 0.0001
  epochs: 2
evaluate:
  batch_size: 4
  eval_score_path: '../eval_score'
visualize:
  vis_num_images: 4
  vis_save_path: '../comparison_model_output_images'
  max_vis: 10
dataset:
  subset_percentage: 0.9